/**
 * Author:  AlexanDev_CWA
 * Created: Jul 26, 2024
 */
CREATE DATABASE cofidi_database;

CREATE ROLE cofidi_client 
    WITH LOGIN NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE PASSWORD 'cofidi123';

GRANT CONNECT ON DATABASE cofidi_database TO cofidi_client;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO cofidi_client;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO cofidi_client;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO cofidi_client;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO cofidi_client;
 
CREATE TABLE clients (
    cli_id SERIAL PRIMARY KEY,
    cli_nam VARCHAR(75) NOT NULL,
    cli_add VARCHAR(150) NOT NULL,
    cli_nit VARCHAR(12) NOT NULL UNIQUE,
    cli_ema VARCHAR(45) NOT NULL UNIQUE,
    cli_pws VARCHAR(100) NOT NULL,    
    cli_pho VARCHAR(10) NOT NULL UNIQUE,
    cli_sys TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cli_upd TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION FUNC_CLIENTS_CLI_UPD ()
RETURNS TRIGGER AS $$
BEGIN
    NEW.cli_upd := CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER TR_CLIENTS_CLI_UPD
AFTER UPDATE ON clients
    FOR EACH ROW
    EXECUTE FUNCTION FUNC_CLIENTS_CLI_UPD();